Azure/acr-cli

- Dockerfile
- README.md
- acr.sh
- cmd/acr/purge.go
- cmd/api/acrsdk.go
- go.mod
- go.sum
When run inside an ACR task the container image is now able to receive the credentials from the task.
An example of a run is
az acr run --cmd "{{ .Run.Registry }}/purge:latest -r {{ .Run.Registry }} -n reponame -a 10d -f '^hello.*'" /dev/null
This would delete all tags that are older than 10 days and their names begin with hello
(Assuming the acr-cli is built as a docker image named /purge:latest in the same registry)
Fixes #3
> Credentials obtained automatically when run in ACR Tasks

- cmd/worker/collector.go
- cmd/worker/purge_structures.go
- cmd/worker/worker.go
- Running `make` fails for the project right now:
> cmd/worker/purge_structures.go:28:6: type name will be used as worker.WorkerError by other packages, and that stutters; consider calling this Error (golint)
- Rename WorkerError to `workerError`, since it doesn't need to be exported right now. Otherwise it could be renamed as just `Error`
> Rename WorkerError to workerError

- Windows.Dockerfile
This PR adds a dockerfile that supports the acr-cli on windows platforms.
The dockerfile is heavily based on the acr-builder one, just made some minimal changes to have it working with acr-cli 
- 
Fixes #39
> Windows Dockerfile added

- cmd/acr/manifest.go
- cmd/acr/purge.go
- cmd/acr/root.go
- cmd/acr/tag.go
If the registry flag is not specified the program looks for the ACR_DEFAULT_REGISTRY environment variable instead, making the registry flag not required.
- 
Fixes #33 
Fixes #34
> Lookup for environment variable added

- cmd/acr/manifest.go
- cmd/acr/purge.go
- cmd/acr/tag.go
- cmd/api/acrsdk.go
- cmd/api/acrsdk_test.go
- cmd/worker/worker.go
This PR adds token refreshing when using bearer authentication, also when a repository is not found or an image is not found or locked the program just prints the issue, instead of returning an error
- 
Fixes #35 
Fixes #38
> Refresh of jwt tokens added

- azure-pipelines-windows.yml
In this PR the windows azure pipeline will not try to fetch dependencies from GitHub and instead it will look for them in the vendor folder.
> Windows pipeline upgrade to not fetch dependencies

- README.md
1. fixes the second `docker build` command which is missing a `.` as an argument
2. fixes the `az acr` commands which are missing the required parameter `--registry`
3. fixes minor formatting issues found by [mdl](https://github.com/markdownlint/markdownlint)
> Fix cli arguments for `az acr` and `docker build`

- cmd/worker/worker.go
**Purpose of the PR**  
Fix #65
- 
Fixes #
Add a nil check to avoid "invalid memory address or nil pointer dereference" error.
> Fix: purge may encounter nil pointer error

- cmd/acr/purge.go
- cmd/acr/purge_test.go
- Refactoring code to get lastTag.
- Current logic fails when using orderBy
- See https://github.com/Azure/acr-cli/pull/72#issuecomment-664201313
> Refactoring last tag from Link Header

- cmd/acr/purge.go
Add nil check to avoid nil pointer error when server does not return correctly
> Add nil check to avoid nil pointer error

- cmd/acr/purge_test.go
- cmd/api/acrsdk.go
- go.mod
- go.sum
- This PR upgrades from dgrijalva/jwt-go to golang-jwt/jwt/v4 since dgrijalva/jwt-go was marked as vulnerable
> Upgrade from dgrijalva/jwt-go to golang-jwt/jwt/v4

- .gitignore
- cmd/acr/purge.go
- cmd/acr/purge_test.go
- Loop to get all the repository names for later regexp filter
Fixes #93
> FIX: loop to get all the repository names

- cmd/acr/purge.go
#107 Improved the output message in dry run mode. Added one message making clear that nothing will be deleted, and changed the wording for dry run output.
Output after the change:
```
$ ./bin/acr purge \
--registry wxxfirstcontainerregistry.azurecr.io \
--filter "app:^hello.*" \
--ago 10d 
Number of deleted tags: 0
Number of deleted manifests: 0
$ ./bin/acr purge \
--registry wxxfirstcontainerregistry.azurecr.io \
--filter "app:^hello.*" \
--ago 10d \
--dry-run
DRY RUN: The following output shows what WOULD be deleted if the purge command was executed. Nothing is deleted.
Number of tags to be deleted: 0
Number of manifests to be deleted: 0
```
> added one message at the beginning of dryRunPurge

- cmd/acr/purge.go
- Changed confusing message in `acr purge` with --dry-run flag set
I found it confusing that the `acr purge` command with --dry-run flag set informs me that the whole repositories would be deleted rather than tags in the repository if I used the command without the flag set.  I believe that the message is now more informative and unambiguous.
> Change confusing dry-run message

- cmd/api/acrsdk.go
Signed-off-by: wangxiaoxuan273 <wangxiaoxuan119@gmail.com>
Fixes #127 
E2E result is successful. `az acr run --cmd "$registry/acr-cli purge --filter 'busybox:.*' --ago 1d --untagged --dry-run" --registry $registry /dev/null`
> fix: fallback to refresh token when loading from docker config file

- cmd/acr/purge.go
- cmd/acr/purge_test.go
The purge command attempts to detect if manifest lists are being used, and will avoid deleting manifests that are part of them.
[The OCI specification defines an index media type](https://github.com/opencontainers/image-spec/blob/main/image-index.md), that can contain manifests as well, as an alternative to manifest lists - functionally, these are the same as manifest lists, and [ACR appears to support them](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-oci-artifacts).
The purge command should therefore avoid removing manifests that are part of indexes as well, which, if the user is using OCI images, will cause their images to be unintentionally deleted.
See https://github.com/docker/build-push-action/issues/778#issuecomment-1406386711 for more information, …
> purge: do not delete contents of oci indexes

- cmd/api/acrsdk.go
- go.mod
- add complete oci and docker image media-type to the accept header
Fixes #131
NOTE: #130 added the multi-arch support for oci image index but the command could still run into the error `[{"errors":[{"code":"MANIFEST_UNKNOWN","message":"OCI index found, but accept header does not support OCI indexes"}]}]`. The pr addresses the problem.
> fix: support oci image index

- .github/workflows/release-github.yml
- .goreleaser.yml
the achrives.replacements field in goreleaser.yml is deprecated so our Action will throw error during release. 
- 
Fixes #
> fix: update deprecated fields in goreleaser

- .github/CODEOWNERS
- Dockerfile
- Makefile
- azure-pipelines.yml
- enable cgo to work with golang 1.22 + FIPS enabled
- add docker build in pr validation
- update owner list
Fixes #261
> fix: docker build with golang 1.22 + FIPS enabled

- .github/workflows/release-github.yml
- fix release issue due to incompatible go version 
Fixes #300
> chore: upgrade go version from 1.18.1 to 1.21 in releaser action

- cmd/acr/cssc.go
- cmd/acr/root.go
- Changes to enable cssc command only when cssc experimental environment variable is set as true
- Renamed flag filter-file-path to filter-policy-file based on a review comment in the spec
Fixes #
- none
> feat: Updated cssc patch command

- cmd/acr/annotate.go
- cmd/acr/purge.go
- cmd/common/image_functions.go
This addresses a minor codeql issue leading to pipeline failures due to trying to cast an uint64 time value to time.Duration (which is a type alias for int(64). This can cause an overflow. Changed to use regular int64.
> Change filtertimeout var from uint64 to int64

- README.md
- cmd/acr/annotate.go
- cmd/acr/purge.go
- cmd/acr/purge_test.go
- cmd/common/image_functions.go
From an empirical observation, listing the repositories is `O(# of OCI objects)` and not `O(# of repositories)`. Therefore, what happens when a registry contains repositories with many objects (like hundred of thousands), listing repositories in batch of 100 breaks with an HTTP 502 because the gateway is taking too long list the repositories.
This PR makes the batch size configurable such that these scenarios can be handled. Setting it to a smaller number like `5` just works as the total time spent in the gateway to list fewer repositories is less than the timeout.
I followed the `concurrency` flag pattern.
> Make the number of repository fetched at once configurable to handle large registries

- internal/cssc/cssc.go
- internal/cssc/cssc_test.go
- When tag-convention is not specified, default it to incremental (new behavior) instead of floating (old behavior) to address a change request from the upstream team
Fixes #
- None
> CSSC - Defaulting tag-convention to incremental

- internal/cssc/cssc.go
- internal/cssc/cssc_test.go
- Code changes to return unique set of matching filtered repos
- Added 2 new unit tests to test for this scenario
Bug: https://msazure.visualstudio.com/AzureContainerRegistry/_workitems/edit/31695069/?view=edit
Before Fix:
After Fix:
> fix(cssc): 31695069 Fix to return unique set of repos and tags in filteredRepos

- Dockerfile
- Windows.Dockerfile
- azure-pipelines-windows.yml
- azure-pipelines.yml
- go.mod
- scripts/setup/dev_setup
> chore: upgrade golang to 1.24.2

- cmd/common/image_functions.go
It should be ignored if manifest not found instead of return error and interrupt all the process
- Fixes #459
> fix: improve error handling in UpdateForManifestWithoutSubjectToDelete

- Windows.Dockerfile
- azure-pipelines-windows.yml
- azure-pipelines.yml
- go.mod
> chore: update golang to 1.24.6
