Azure/acr-cli

cmd/acr/purge.go
cmd/worker/collector.go
cmd/worker/dispatcher.go
cmd/worker/purge_structures.go
cmd/worker/worker.go

In order to not saturate the registry now only six request are done at the same time
Fixes #7

Worker pool added to have a fixed amount of concurrent calls.

---

cmd/acr/purge.go

- Enable overriding default concurrency
Fixes #16

Enable overriding default concurrency

---

Dockerfile
auth/client.go
auth/docker/credential.go
cmd/acr/purge.go
cmd/acr/root.go
cmd/acr/tag.go

- Add local basic auth. The OAuth workflow is still a WIP.

Add local basic auth

---

cmd/acr/login.go
cmd/acr/manifest.go
cmd/acr/purge.go
cmd/acr/root.go
cmd/acr/tag.go
cmd/api/acrsdk.go
go.mod

This PR includes new functionality for the tag command as well as a new command: manifest.
Also there are new options for login such as interactive mode and password from stdin
The dry-run flag allows users to view what would be purged before anything is deleted.
Finally there is some code refactoring.
- 
Fixes #25
Fixes #24 
Fixes #22 
Fixes #21 
Fixes #18

T gigo/auth features

---

README.md
cmd/acr/login.go
cmd/acr/manifest.go
cmd/acr/purge.go
cmd/acr/tag.go
cmd/api/acrsdk.go

This PR expands the README file and also expands some of the help messages for the project.
- 
Fixes #10

README file expanded and help messages changed

---

Makefile.windows

- Add Windows Makefile settings (allows you to build `acr.exe`)

Add Windows Makefile settings

---

cmd/acr/purge.go
cmd/worker/worker.go

This PR adds support for interacting with registries that have multiarchitecture or manifest lists in them, with the previous behavior the dangling manifests would be deleted no matter what, and if they were referenced by a manifest list they would still get deleted and the original multiarchitecture manifest would have been left not fully functional, this PR addresses this by before purging dangling manifests scanning to find multiarchitecture manifests and by not deleting if they were referenced by a manifest that would not get deleted.

Multiarchitecture support added

---

README.md
cmd/acr/purge.go
cmd/worker/collector.go
cmd/worker/purge_structures.go
cmd/worker/worker.go

This PR removes the archive feature, adds a summary at the end of the run, removes the repository flag, 
enhances the filter flag functionality as well as making it required and adds support for having multiple filters.

T gigo/fixes

---

azure-pipelines.yml

update build command

---

README.md
azure-pipelines-windows.yml
azure-pipelines.yml

This small PR contains a basic pipeline definition for making the program compiles on a windows hosted agent.

Windows pipeline added

---

azure-pipelines-windows.yml
cmd/acr/purge.go
cmd/worker/worker.go
go.mod
vendor/modules.txt

This PR introduces a more robust way to skip tags and manifests that have the delete enabled attribute set to false.

Delete enabled=false codition implemented in a clearer way

---

README.md
cmd/acr/purge.go
cmd/acr/purge_test.go

- Add `--keep` flag
Fixes https://github.com/Azure/acr-cli/issues/69

Add keep flag

---

azure-pipelines-windows.yml
azure-pipelines.yml

- Update Azure DevOps agent version
Fixes #89

fix vm image version

---

vendor/github.com/dlclark/regexp2/.gitignore
vendor/github.com/dlclark/regexp2/.travis.yml
vendor/github.com/dlclark/regexp2/ATTRIB
vendor/github.com/dlclark/regexp2/LICENSE
vendor/github.com/dlclark/regexp2/README.md
vendor/github.com/dlclark/regexp2/match.go
vendor/github.com/dlclark/regexp2/regexp.go
vendor/github.com/dlclark/regexp2/replace.go
vendor/github.com/dlclark/regexp2/runner.go
vendor/github.com/dlclark/regexp2/syntax/charclass.go
vendor/github.com/dlclark/regexp2/syntax/code.go
vendor/github.com/dlclark/regexp2/syntax/escape.go
vendor/github.com/dlclark/regexp2/syntax/fuzz.go
vendor/github.com/dlclark/regexp2/syntax/parser.go
vendor/github.com/dlclark/regexp2/syntax/prefix.go
vendor/github.com/dlclark/regexp2/syntax/replacerdata.go
vendor/github.com/dlclark/regexp2/syntax/tree.go
vendor/github.com/dlclark/regexp2/syntax/writer.go
vendor/github.com/dlclark/regexp2/testoutput1
vendor/modules.txt

ran `go mod vendor` to make up what last commit missed.

ran 'go mod vendor' to make up what last commit missed

---

cmd/acr/purge_test.go

- Adding additional test cases

Maint. Adding more test coverage

---

.github/workflows/release-github.yml
.goreleaser.yml

Signed-off-by: wangxiaoxuan273 <wangxiaoxuan119@gmail.com>
- Added automatic release pipeline. A draft release with built binaries is created when we push a versioned tag.
Fixes #109 , resolves #109 once merged.

added automated GitHub release

---

Dockerfile

Migrated acr cli image from docker to mariner.

migrate acr cli image to mariner

---

.github/CODEOWNERS

chore: update owner

---

cmd/acr/purge.go
cmd/acr/purge_test.go

fix(purge): skip tag/manifest with false writeEnabled attribute

---

auth/oras/store.go
cmd/acr/login.go
cmd/acr/logout.go
cmd/acr/manifest.go
cmd/acr/purge.go
cmd/acr/root.go
cmd/acr/tag.go
cmd/acr/version.go
cmd/api/acrsdk_test.go

Following pr #128 
Related: `Azure/go-autorest` is going to be out of support very soon. [Link](https://github.com/Azure/go-autorest)

test: add unit tests for GetAcrCLIClientWithAuth

---

Dockerfile

chore: update mariner base image

---

Dockerfile
go.mod
go.sum

chore: update to golang 1.21

---

.golangci.yml
auth/oras/client.go
azure-pipelines.yml
cmd/acr/login.go
cmd/acr/logout.go
cmd/acr/manifest.go
cmd/acr/purge.go
cmd/acr/tag.go
cmd/acr/version.go

Update the go version and fix linter errors

chore: update go version for azure pipelines

---

.github/CODEOWNERS

Add Ruchi to code owners.
Fixes #

Add @Ruchii-27 to Codeowners

---

Dockerfile
Windows.Dockerfile
azure-pipelines-windows.yml
azure-pipelines.yml
go.mod

chore: update golang to 1.24.4

---

Windows.Dockerfile
azure-pipelines-windows.yml
azure-pipelines.yml
go.mod

chore: update golang to 1.24.5

---

cmd/acr/annotate_test.go
internal/worker/purger.go

- Fixes lint errors caused by my PR (#479)

fix: lint errors caused by #479
